### ISSUE TITLE
Update evaluation order on D&D

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#17]
When D&D is complete, be sure to calculate the new evaluation order. For this, you will need to know the evaluation order of the entry before/after the target area, and subtract/add 1 from/to the new entry. 

A - 1
B - 2
C - 3

Dragging B could result into:

A - 1
C - 3
B - 4

or 

B - 0
A - 1
C - 3

Negative results, or those that are greater than 2147483647 are not allowed. So disable the drop target if it results into a bad order.

**Comment by mmoayyed** [comment]
On the drop, you'll need to contact the server of course to make the change and persist it. The server will tell you if it could, so you can render the result and present a message to the user, etc.

**Comment by darkape** [comment]
"Negative results, or those that are greater than 2147483647 are not allowed. So disable the drop target if it results into a bad order."

I'll check, but pretty sure the sorting is 0- or 1-based as the root and part of the A/C is that there should only be about 15-20 of these, not more; was important since I was considering pagination for the page. Will try to keep this in mind for the validation of the form's evalOrder field though.

**Comment by darkape** [comment]
Just pointing this out, but this Issue contradicts #11, which I didn't realize until after my commit and was looking for more to knock out. =P

**Comment by mmoayyed** [comment]
So documenting the summary of our discussion for record keeping: 

Evaluation Order should not be listed on the dashboard; because services are auto sorted by evaluation order when you retrieve them. So the fact that they are visually ordered should suffice, I hope. You nonetheless always get the evaluation order in the payload. Just dont render is, and solely use/update it for D&D. 

I dont think the UI has any options for sorting by other cols, which is fine. Not needed in fact.

**Comment by mmoayyed** [comment]
This isn't quite right yet; because it seems like you're changing two entries. The entry that is being moved changes, and the its neighbor. This may not work because you'll end up sending two calls to the server to update both. Is that what you had in mind? 

Note that evaluation orders do not have to be unique. Two entries could both have the same evaluation order. So if you move an entry and that move results into getting the same evaluation order as some other entry because ur calc made it so, that's fine.

**Comment by darkape** [comment]
... The purpose of the drag-and-drop (DaD) isn't valid then (in my opinion) if they need the ability to have over-lapping evalOrder values though it since the DaD orders a list sequentially, there is no sharing of the same positioning. As for what DaD is doing, it is not changing just two values, it is currently changing the value of all entries in the sorting list.

**Comment by mmoayyed** [comment]
Having two entries with the same evaluation order is definitely a bad idea, but it's technically possible and isn't considered a technical error, more like a logical "this doesn't make sense and can lead into weird behavior" error. That said, I definitely dont think you should change all entries in the list. You should only take note of the drop target's entries and update that entry with respect to the previous/next entry (as my example above feebly attempts to demonstrate) If the result is duplicate eval orders, so be it. Let the adopter fix that. At the end, only one call should be made to the server for the entry that is actually being moved.

**Comment by darkape** [comment]
>>  At the end, only one call should be made to the server for the entry that is actually being moved.

Why? If it is a performance issue, we can cut back the entries send for updating to only ones with values changed - http://stackoverflow.com/questions/16894148/detect-if-element-position-was-changed-in-jquery-ui-sortable.

There are still several problems with what you've mentioned you want: the positioning is still integer based, so if you drag an entry between two items (let's say dragging 5 between 2 and 3), then the list cannot make the previously no.5 item now be 2.5, nor 2 or 3 since those spots are unique entries - like array indexing, but the values only accept a single, non-complete item.

**Comment by mmoayyed** [comment]
That might work; I am just you may want to delegate all that work to the user, but it can be made to work so you only send updates for the entries that changed, then no problem.
