### ISSUE TITLE
Delete button should confirm removal first

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#23]
The delete butto should confirm removals before doing anything. Presently, it opens the quick view for the entry

**Comment by darkape** [comment]
Going to need a rest URL to shoot the POST request to.

**Comment by darkape** [comment]
For the record, this is not as easy as I thought it would be because we can't dynamically create the modals with <spring:message /> in them; I tried passing it as bound HTML but fails to render. I'd suggest if we continue with Angular that we switch the messages to a JSON so that we can render it from the front-end since it would not only help with with the JS, but we could also make the HTML tags smaller and have it parsed by an Angular filter.

Another problem I've run into is that I get errors about missing headers when I try to build after creating a new JS file. How can I fix this problem? I will at least need to eventually break the modules, controllers, and directives into their own files.

**Comment by mmoayyed** [comment]
So, lets not do a modal screen. Can we simply replace the edit button with an inline panel that does show yes/no buttons? perhaps an alternative approach would to use spring-message inside a hidden div that you get to show when you present the dialog and the div then becomes visible? the message is pre rendered then. 

What headers do you speak of? Provide an example please.

**Comment by darkape** [comment]
Currently working on an approach with the modal block in the JSP template. It isn't perfect or what I'd like for dynamic usage, but should work well if I can solve the current display problem. If all else fails, we'll drop the modal, but it would be helpful if we had modals working for the app in general.

Asked in channel about the headers and was pointed to Jodie who informed me that all new files need the <%-- Licence --%> block at the top of them, which solves the "Missing header in" issue that was occurring.

**Comment by mmoayyed** [comment]
ah yeah, ok. If you need an automated way to generate license headers, simply execute:

mvn license:format

If you want to check and see if you have missed something:

mvn license:check
