### ISSUE TITLE
Provide update URL for D&D on the dashboard

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#28]
The drop should contact the server with a new evaluation order.

**Comment by mmoayyed** [comment]
I'll provide the new ur here.

**Comment by mmoayyed** [comment]
Submit a GET request to:

/cas-management/updateRegisteredServiceEvaluationOrder.html?id=<service numeric id>&evaluationOrder=<eval order>

id=the service whose eval order should be updated
eval order=the new order value

You will get an error back via JS if update fails. Otherwise assume things were executed correctly.

**Comment by darkape** [comment]
Anytime we sort, we're changing more than just a single service item, so need a method that accepts multiple items at once rather than several single calls. For example, I could pass id[]=11234&id[]=43021&id[]=90432 and then those three get updated by their indexing.

**Comment by mmoayyed** [comment]
Define "by their indexing". Whichever comes first in the request? That wont work because I'd also need to know the evaluation order. I think I was under the assumption that D&D only changes one item at a time and that collissions are acceptable?  Not true?

**Comment by darkape** [comment]
By indexing, I mean that id[] should be able to parse to an array, which would put them in the order they are sent, so you'd have [11234, 4302, 90432] once parsed, which is then in the same evaluation order as it was sorted and sent.

As I mentioned previously in Issue #17, collisions cannot happen with the sortable list because jQuery is treating the items as an array and thus cannot have duplicate entries through the drag-and-drop interface; it is possible if they go an edit a service, but any sort afterwards will fix it.

**Comment by mmoayyed** [comment]
OK, I see. I am just very uneasy with that approach because it just comes up as a surprise. Let me elaborate:

You have 11234, 4302, 90432, with evaluation orders such as 0,1,2. That's fine. Then, I go into the edit screen and I change the evaluation order for 4302 to be 100. The list is then changed to 11234, 90432, 4302. So far so good. 

Then I decide to drag 90432 somewhere, and as a result, all my evaluation orders are changed. That is not acceptable. I wouldn't call that a fix. I'd propose some some of abstraction layer that is on top of jquery that is able to handle duplicate items.  We really can't have the entire list changing.

**Comment by darkape** [comment]
Why not remove evalOrder from the editable fields of the form and assign it a fixed value? Something like 100 when a new one is created so that they are always added to the end of the list. Then ANY sorting fixes the numbers since it isn't the # itself that is important but the ordering of the services themselves. If that is no good, then we just need to drop D&D.

**Comment by mmoayyed** [comment]
I had a chance to think this over, and that's a good idea. Lets do that. I'll also work on making sure that id can turn into an array for that endpoint.

**Comment by mmoayyed** [comment]
This is done. Please pull

**Comment by darkape** [comment]
So is the URL now "/cas-management/updateRegisteredServiceEvaluationOrder.html?X" with X being the id[]=#&id[]=#&id[]=# string?

**Comment by mmoayyed** [comment]
Yes, to be exact, X=> id=1&id=2&id=3. It will auto-turn into an array.

**Comment by darkape** [comment]
Okay, so I need to pull out the "[]". Can do.

**Comment by darkape** [comment]
Any particular reason this request and the Delete one are GETs and not PUT/POST? Just seems odd to me.

**Comment by mmoayyed** [comment]
No, dont think so. I am just working with code that was there from the beginning. Would you rather they turn into a POST?

**Comment by darkape** [comment]
Please and thank you. GET expose all of our data to see and are typically only used when requesting data and has restrictions in type & length of data that we are able to send when compared to POST.

**Comment by mmoayyed** [comment]
got it. will adjust shortly.

**Comment by darkape** [comment]
Same error is happening as the call for Delete modal as mentioned in Issue #23

**Comment by mmoayyed** [comment]
Adam, go ahead and commit the changes as you have. This will likely require some debugging on my part. I want to see what the incoming request is, and how CAS processes it at the given endpoint.
