### ISSUE TITLE
Return back to the dashboard when save?

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#68]
Dont know if this is intentional but:

1. When I save an entry, I am not taken back to the dashboard
2. I also dont see a message to tell me if data was saved successfully

**Comment by darkape** [comment]
There is code in place that should show an inline alert saying the save was a success, so not sure why you aren't seeing it. I kept getting errors when saving yesterday, so I wasn't able to confirm it working, but I'll check once the build is working again with your latest changes. Currently I don't plan to have the form auto-direct to the dashboard on save since I have the code for the 'Saved' alert in there.

**Comment by darkape** [comment]
Okay, alert was in place, but the message itself was missing. Fixed.

**Comment by mmoayyed** [comment]
Thanks
